---
version: 2.1

executors:
  ansible-lint:
    docker:
      - image: ghcr.io/docker-images-mamono210/circleci-executors/ansible-lint:latest
    resource_class: small
  molecule:
    docker:
      - image: ghcr.io/docker-images-mamono210/circleci-executors_molecule/molecule:ec2
    resource_class: medium
  yamllint:
    docker:
      - image: ghcr.io/docker-images-mamono210/circleci-executors/yamllint:latest
    resource_class: small
  trailing-whitespace:
    docker:
      - image: ghcr.io/docker-images-mamono210/circleci-executors/trailing-whitespace:latest
    resource_class: small

orbs:
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  ansible-lint:
    executor: ansible-lint
    steps:
      - checkout
      - run:
          name: Install galaxy roles
          command: |
            ansible-galaxy install -r molecule/redmica/requirements.yml
      - run:
          name: Execulte Ansible-lint
          command: ansible-lint
      - run:
          name: Show Ansible-lint version
          command: |
            pip list | grep ansible \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
            ansible-lint --version
  molecule:
    executor: molecule
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
          role-arn: ${AWS_ROLE_ARN}
          role-session-name: circleci_ansible-playbook_redmine_restore
          session-duration: '1800'
      - run:
          name: Set AWS credentials to environment variables
          command: |
            AWS_ACCESS_KEY_ID=`cat ~/.aws/credentials | grep aws_access_key_id | awk '{print $3}'`
            AWS_REGION=`cat ~/.aws/config | grep region | awk '{print $3}'`
            AWS_SECRET_ACCESS_KEY=`cat ~/.aws/credentials | grep aws_secret_access_key | awk '{print $3}'`
            AWS_SESSION_TOKEN=`cat ~/.aws/credentials | grep aws_session_token | awk '{print $3}'`
            echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $BASH_ENV
            echo "AWS_REGION=${AWS_REGION}" >> $BASH_ENV
            echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $BASH_ENV
            echo "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Set latest AMI image id to environment variables
          command: |
            AMI_ID=$(aws ec2 describe-images \
            --owners ${AMI_OWNER_ID} \
            --filters "Name=name,Values=redmica_golden-image_centos-stream8*" \
            --query 'Images[*][CreationDate, ImageId, Name]' \
            --output text | sort -r | awk 'NR==1 {print $2}')
            echo "export AMI_ID=${AMI_ID}" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Set timestamp for making sure Molecule would create unique AWS resources
          command: |
            TIMESTAMP=$(date --date "9 hours" "+%Y%m%d_%H:%M:%S")
            VALUE='molecule_redmine_restore'
            AUTHOR_EMAIL=$(git show -s --format='%ae' ${CIRCLE_SHA1})

            echo "export CREATED_BY=${AUTHOR_EMAIL}" >> $BASH_ENV
            echo "export KEYPAIR_NAME=${VALUE}_${TIMESTAMP}" >> $BASH_ENV
            echo "export PLATFORM_NAME=${VALUE}_${TIMESTAMP}" >> $BASH_ENV
            echo "export SECURITY_GROUP_NAME=${VALUE}_${TIMESTAMP}" >> $BASH_ENV
            echo "export TAG_NAME=${VALUE}_${TIMESTAMP}" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install required Ansible Collections and roles
          command: |
            ansible-galaxy collection install community.molecule
            ansible-galaxy install -r molecule/redmica/requirements.yml
      - run:
          name: Test with molecule
          command: |
            molecule test --scenario-name redmica
          environment:
            ANSIBLE_FORCE_COLOR: '1'
            # AMI_ID: sotred in system environment variables
            # AWS_ACCESS_KEY_ID: sotred in system environment variables
            # AWS_DEFAULT_REGION: sotred in CircleCI environment variables
            # AWS_SECRET_ACCESS_KEY: sotred in system environment variables
            # AWS_SESSION_TOKEN: sotred in system environment variables
            # CREATED_BY: stored in system environment variables
            # EC2_REGION: stored in CircleCI environment variables
            # KEYPAIR_NAME: sotred in system environment variables
            # PLATFORM_NAME: sotred in system environment variables
            PROFILE_TASKS_SORT_ORDER: 'none'
            PROFILE_TASKS_TASK_OUTPUT_LIMIT: '200'
            PY_COLORS: '1'
            # SECURITY_GROUP_NAME: sotred in CircleCI environment variables
            # VPC_SUBNET_ID: sotred in CircleCI environment variables
            TZ: 'Asia/Tokyo'
      - run:
          name: Show Ansible version
          command: |
            pip list | grep ansible \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
            ansible --version
      - run:
          name: Show Molecule version
          command: molecule --version
  yamllint:
    executor: yamllint
    steps:
      - checkout
      - run:
          name: Execute yamllint
          command: yamllint *
      - run:
          name: Show yamllint version
          command: |
            yamllint --version \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'yamllint.* '
  trailing-whitespace:
    executor: trailing-whitespace
    steps:
      - checkout
      - run:
          name: Execute trailing-whitespace
          command: trailing-whitespace

workflows:
  version: 2.1
  build:
    jobs:
      - trailing-whitespace
      - yamllint:
          requires:
            - trailing-whitespace
      - ansible-lint:
          requires:
            - yamllint
      - molecule:
          context: AWS_OPENID_CONNECT_TOKENS
          requires:
            - ansible-lint
